services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: stocks
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://user:userpass@mysql:3306/stocks
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
  
  airflow-scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://user:userpass@mysql:3306/stocks
      ALPHA_VANTAGE_KEY: ${ALPHA_VANTAGE_KEY}
      DB_HOST: mysql
      DB_NAME: stocks
      DB_USER: user
      DB_PASS: userpass
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    command: scheduler

  airflow-webserver:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://user:userpass@mysql:3306/stocks
      ALPHA_VANTAGE_KEY: ${ALPHA_VANTAGE_KEY}
      DB_HOST: mysql
      DB_NAME: stocks
      DB_USER: user
      DB_PASS: userpass
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    command: webserver
